import fs from 'node:fs';

const version = process.argv[2]?.trim();
if (!version || !/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(version)) {
  throw new Error('Usage: npm run version:set -- <major.minor.patch>');
}

fs.writeFileSync(new URL('../VERSION', import.meta.url), `${version}\n`);
for (const file of ['frontend/package.json', 'frontend/package-lock.json', 'service/package.json', 'service/package-lock.json']) {
  const url = new URL(`../${file}`, import.meta.url);
  const data = JSON.parse(fs.readFileSync(url, 'utf8'));
  data.version = version;
  if (file.endsWith('package-lock.json') && data.packages?.['']) data.packages[''].version = version;
  fs.writeFileSync(url, `${JSON.stringify(data, null, 2)}\n`);
}
fs.writeFileSync(
  new URL('../service/src/version.ts', import.meta.url),
  `/** Generated by npm run version:set; VERSION is authoritative. */\nexport const APP_VERSION = '${version}';\n`,
);
console.log(`Prepared Nolizi Sign v${version}. Run npm run version:check, test, stage, then tag the verified commit.`);
